// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eexvimhubsblwtomepkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVleHZpbWh1YnNibHd0b21lcGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzE4NzYsImV4cCI6MjA2NDQ0Nzg3Nn0.I3SbXRgP8a6UQphxwqjecuLXq_sjkDvH5AST4jjjoyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);